# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.my-manager.v3/ui/action_payload.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ActionPayloadContainer(object):
    def setupUi(self, ActionPayloadContainer):
        ActionPayloadContainer.setObjectName("ActionPayloadContainer")
        ActionPayloadContainer.resize(489, 40)
        ActionPayloadContainer.setStyleSheet("#Dialog_User{\n"
"  font-family: \"Courier New\";\n"
"  background-color: #FFFFFF;\n"
"}\n"
"QPushButton{\n"
"  font-family: \"Courier New\";\n"
"}\n"
"QCheckBox {\n"
"  font-family: \"Courier New\";\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"}\n"
"\n"
"QCheckBox{\n"
"  color: #212529;\n"
"}")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ActionPayloadContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.action_name = QtWidgets.QComboBox(parent=ActionPayloadContainer)
        self.action_name.setObjectName("action_name")
        self.horizontalLayout.addWidget(self.action_name)
        self.action_payload = QtWidgets.QComboBox(parent=ActionPayloadContainer)
        self.action_payload.setObjectName("action_payload")
        self.horizontalLayout.addWidget(self.action_payload)
        self.pid_input = QtWidgets.QLineEdit(parent=ActionPayloadContainer)
        self.pid_input.setMinimumSize(QtCore.QSize(120, 0))
        self.pid_input.setStyleSheet("margin: 0 4px;")
        self.pid_input.setObjectName("pid_input")
        self.horizontalLayout.addWidget(self.pid_input)
        self.action_delete_btn = QtWidgets.QPushButton(parent=ActionPayloadContainer)
        self.action_delete_btn.setStyleSheet("")
        self.action_delete_btn.setObjectName("action_delete_btn")
        self.horizontalLayout.addWidget(self.action_delete_btn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(ActionPayloadContainer)
        QtCore.QMetaObject.connectSlotsByName(ActionPayloadContainer)

    def retranslateUi(self, ActionPayloadContainer):
        _translate = QtCore.QCoreApplication.translate
        ActionPayloadContainer.setWindowTitle(_translate("ActionPayloadContainer", "Form"))
        self.action_delete_btn.setText(_translate("ActionPayloadContainer", "Delete"))
