# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.my-manager.v1/ui/dialog_re_product.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_REProduct(object):
    def setupUi(self, Dialog_REProduct):
        Dialog_REProduct.setObjectName("Dialog_REProduct")
        Dialog_REProduct.resize(493, 691)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(13)
        font.setBold(True)
        Dialog_REProduct.setFont(font)
        Dialog_REProduct.setStyleSheet("#Dialog_REProduct {\n"
                                       "  font-family: \"Courier New\";\n"
                                       "  background-color: #FFFFFF;\n"
                                       "}\n"
                                       "QGroupBox {\n"
                                       "  font-family: \"Courier New\";\n"
                                       "  font-size: 13px;\n"
                                       "  background-color: rgba(248, 249, 250, 1);\n"
                                       "}\n"
                                       "QLineEdit {\n"
                                       "  padding: 4px 0;\n"
                                       "  border: 1px solid #ced4da;\n"
                                       "  border-radius: 8px;\n"
                                       "  margin-left: 8px;\n"
                                       "  padding-left: 4px;\n"
                                       "  background-color: #FFFFFF;\n"
                                       "  color:#212529;\n"
                                       "}\n"
                                       "QPlainTextEdit {\n"
                                       "    background-color: #FFFFFF;\n"
                                       "  color:#212529;\n"
                                       "}\n"
                                       "QLabel {\n"
                                       "  font-family: \"Courier New\";\n"
                                       "  font-size: 13px;\n"
                                       "  color: rgb(90, 93, 97);\n"
                                       "}\n"
                                       "QRadioButton {\n"
                                       "  font-family: \"Courier New\";\n"
                                       "  font-size: 13px;\n"
                                       "  color: #212529;\n"
                                       "}\n"
                                       "QComboBox {\n"
                                       "  font-family: \"Courier New\";\n"
                                       "  font-size: 13px;\n"
                                       "  color: #212529;\n"
                                       "}\n"
                                       "QPushButton {\n"
                                       "  color: #212529;\n"
                                       "}\n"
                                       "\n"
                                       "")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_REProduct)
        self.verticalLayout_2.setContentsMargins(4, 8, 8, 8)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_container_w = QtWidgets.QGroupBox(parent=Dialog_REProduct)
        self.image_container_w.setMinimumSize(QtCore.QSize(0, 160))
        self.image_container_w.setStyleSheet("")
        self.image_container_w.setTitle("")
        self.image_container_w.setObjectName("image_container_w")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.image_container_w)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_input = QtWidgets.QLabel(parent=self.image_container_w)
        self.image_input.setMinimumSize(QtCore.QSize(460, 160))
        self.image_input.setStyleSheet("font-weight: 600;\n"
                                       "font-size: 16px;\n"
                                       "color: #343A40;\n"
                                       "border: 2px dashed #CED4DA;\n"
                                       "border-radius: 4px;")
        self.image_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image_input.setObjectName("image_input")
        self.horizontalLayout.addWidget(self.image_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.image_container_w)
        self.option_container_w = QtWidgets.QGroupBox(parent=Dialog_REProduct)
        self.option_container_w.setMaximumSize(QtCore.QSize(16777215, 60))
        self.option_container_w.setTitle("")
        self.option_container_w.setObjectName("option_container_w")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(
            self.option_container_w)
        self.horizontalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.option_sell_radio = QtWidgets.QRadioButton(
            parent=self.option_container_w)
        self.option_sell_radio.setObjectName("option_sell_radio")
        self.horizontalLayout_2.addWidget(self.option_sell_radio)
        self.option_rent_radio = QtWidgets.QRadioButton(
            parent=self.option_container_w)
        self.option_rent_radio.setObjectName("option_rent_radio")
        self.horizontalLayout_2.addWidget(self.option_rent_radio)
        self.option_assignment_radio = QtWidgets.QRadioButton(
            parent=self.option_container_w)
        self.option_assignment_radio.setObjectName("option_assignment_radio")
        self.horizontalLayout_2.addWidget(self.option_assignment_radio)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.option_container_w)
        self.basic_container_w = QtWidgets.QGroupBox(parent=Dialog_REProduct)
        self.basic_container_w.setMaximumSize(QtCore.QSize(16777215, 67))
        self.basic_container_w.setTitle("")
        self.basic_container_w.setObjectName("basic_container_w")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.basic_container_w)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.categories_combobox = QtWidgets.QComboBox(
            parent=self.basic_container_w)
        self.categories_combobox.setObjectName("categories_combobox")
        self.categories_combobox.addItem("")
        self.gridLayout.addWidget(self.categories_combobox, 0, 3, 1, 1)
        self.pid_input = QtWidgets.QLineEdit(parent=self.basic_container_w)
        self.pid_input.setEnabled(True)
        self.pid_input.setMinimumSize(QtCore.QSize(140, 0))
        self.pid_input.setReadOnly(True)
        self.pid_input.setObjectName("pid_input")
        self.gridLayout.addWidget(self.pid_input, 0, 1, 1, 1)
        self.pid_label = QtWidgets.QLabel(parent=self.basic_container_w)
        self.pid_label.setObjectName("pid_label")
        self.gridLayout.addWidget(self.pid_label, 0, 0, 1, 1)
        self.statuses_combobox = QtWidgets.QComboBox(
            parent=self.basic_container_w)
        self.statuses_combobox.setObjectName("statuses_combobox")
        self.statuses_combobox.addItem("")
        self.gridLayout.addWidget(self.statuses_combobox, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.basic_container_w)
        self.location_container = QtWidgets.QGroupBox(parent=Dialog_REProduct)
        self.location_container.setMaximumSize(QtCore.QSize(16777215, 114))
        self.location_container.setStyleSheet("QLabel{\n"
                                              "font-family: \"Courier New\";\n"
                                              "font-size: 10px;\n"
                                              "}")
        self.location_container.setTitle("")
        self.location_container.setObjectName("location_container")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.location_container)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.wards_combobox = QtWidgets.QComboBox(
            parent=self.location_container)
        self.wards_combobox.setObjectName("wards_combobox")
        self.wards_combobox.addItem("")
        self.gridLayout_3.addWidget(self.wards_combobox, 0, 2, 1, 1)
        self.districts_combobox = QtWidgets.QComboBox(
            parent=self.location_container)
        self.districts_combobox.setObjectName("districts_combobox")
        self.districts_combobox.addItem("")
        self.gridLayout_3.addWidget(self.districts_combobox, 0, 1, 1, 1)
        self.provinces_combobox = QtWidgets.QComboBox(
            parent=self.location_container)
        self.provinces_combobox.setObjectName("provinces_combobox")
        self.provinces_combobox.addItem("")
        self.gridLayout_3.addWidget(self.provinces_combobox, 0, 0, 1, 1)
        self.location_street_container_w = QtWidgets.QWidget(
            parent=self.location_container)
        self.location_street_container_w.setObjectName(
            "location_street_container_w")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.location_street_container_w)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.street_label = QtWidgets.QLabel(
            parent=self.location_street_container_w)
        self.street_label.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.street_label.setFont(font)
        self.street_label.setLineWidth(1)
        self.street_label.setIndent(-1)
        self.street_label.setObjectName("street_label")
        self.verticalLayout_3.addWidget(self.street_label)
        self.street_input = QtWidgets.QLineEdit(
            parent=self.location_street_container_w)
        self.street_input.setObjectName("street_input")
        self.verticalLayout_3.addWidget(self.street_input)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addWidget(
            self.location_street_container_w, 1, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.location_container)
        self.detail_container_w = QtWidgets.QGroupBox(parent=Dialog_REProduct)
        self.detail_container_w.setStyleSheet("QLabel{\n"
                                              "font-family: \"Courier New\";\n"
                                              "font-size: 10px;\n"
                                              "}")
        self.detail_container_w.setTitle("")
        self.detail_container_w.setObjectName("detail_container_w")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.detail_container_w)
        self.gridLayout_6.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.price_container_w = QtWidgets.QWidget(
            parent=self.detail_container_w)
        self.price_container_w.setObjectName("price_container_w")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.price_container_w)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.price_label = QtWidgets.QLabel(parent=self.price_container_w)
        self.price_label.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.price_label.setFont(font)
        self.price_label.setLineWidth(1)
        self.price_label.setIndent(-1)
        self.price_label.setObjectName("price_label")
        self.verticalLayout_9.addWidget(self.price_label)
        self.price_input = QtWidgets.QLineEdit(parent=self.price_container_w)
        self.price_input.setObjectName("price_input")
        self.verticalLayout_9.addWidget(self.price_input)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.gridLayout_5.addWidget(self.price_container_w, 1, 0, 1, 1)
        self.furniture_s_combobox = QtWidgets.QComboBox(
            parent=self.detail_container_w)
        self.furniture_s_combobox.setObjectName("furniture_s_combobox")
        self.furniture_s_combobox.addItem("")
        self.gridLayout_5.addWidget(self.furniture_s_combobox, 2, 0, 1, 1)
        self.building_line_s_combobox = QtWidgets.QComboBox(
            parent=self.detail_container_w)
        self.building_line_s_combobox.setObjectName("building_line_s_combobox")
        self.building_line_s_combobox.addItem("")
        self.gridLayout_5.addWidget(self.building_line_s_combobox, 2, 1, 1, 1)
        self.function_container_w = QtWidgets.QWidget(
            parent=self.detail_container_w)
        self.function_container_w.setObjectName("function_container_w")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(
            self.function_container_w)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.function_label = QtWidgets.QLabel(
            parent=self.function_container_w)
        self.function_label.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.function_label.setFont(font)
        self.function_label.setLineWidth(1)
        self.function_label.setIndent(-1)
        self.function_label.setObjectName("function_label")
        self.verticalLayout_11.addWidget(self.function_label)
        self.function_input = QtWidgets.QLineEdit(
            parent=self.function_container_w)
        self.function_input.setObjectName("function_input")
        self.verticalLayout_11.addWidget(self.function_input)
        self.verticalLayout_10.addLayout(self.verticalLayout_11)
        self.gridLayout_5.addWidget(self.function_container_w, 1, 1, 1, 3)
        self.structure_container_w = QtWidgets.QWidget(
            parent=self.detail_container_w)
        self.structure_container_w.setObjectName("structure_container_w")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(
            self.structure_container_w)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.structure_label = QtWidgets.QLabel(
            parent=self.structure_container_w)
        self.structure_label.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.structure_label.setFont(font)
        self.structure_label.setLineWidth(1)
        self.structure_label.setIndent(-1)
        self.structure_label.setObjectName("structure_label")
        self.verticalLayout_7.addWidget(self.structure_label)
        self.structure_input = QtWidgets.QLineEdit(
            parent=self.structure_container_w)
        self.structure_input.setObjectName("structure_input")
        self.verticalLayout_7.addWidget(self.structure_input)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addWidget(self.structure_container_w, 0, 2, 1, 2)
        self.area_container_w = QtWidgets.QWidget(
            parent=self.detail_container_w)
        self.area_container_w.setObjectName("area_container_w")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.area_container_w)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.area_label = QtWidgets.QLabel(parent=self.area_container_w)
        self.area_label.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.area_label.setFont(font)
        self.area_label.setLineWidth(1)
        self.area_label.setIndent(-1)
        self.area_label.setObjectName("area_label")
        self.verticalLayout_25.addWidget(self.area_label)
        self.area_input = QtWidgets.QLineEdit(parent=self.area_container_w)
        self.area_input.setObjectName("area_input")
        self.verticalLayout_25.addWidget(self.area_input)
        self.verticalLayout_24.addLayout(self.verticalLayout_25)
        self.gridLayout_5.addWidget(self.area_container_w, 0, 0, 1, 2)
        self.description_container_w = QtWidgets.QWidget(
            parent=self.detail_container_w)
        self.description_container_w.setObjectName("description_container_w")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(
            self.description_container_w)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.description_label = QtWidgets.QLabel(
            parent=self.description_container_w)
        self.description_label.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.description_label.setFont(font)
        self.description_label.setLineWidth(1)
        self.description_label.setIndent(-1)
        self.description_label.setObjectName("description_label")
        self.verticalLayout_23.addWidget(self.description_label)
        self.description_input = QtWidgets.QPlainTextEdit(
            parent=self.description_container_w)
        self.description_input.setObjectName("description_input")
        self.verticalLayout_23.addWidget(self.description_input)
        self.verticalLayout_22.addLayout(self.verticalLayout_23)
        self.gridLayout_5.addWidget(self.description_container_w, 3, 0, 1, 4)
        self.legal_s_combobox = QtWidgets.QComboBox(
            parent=self.detail_container_w)
        self.legal_s_combobox.setObjectName("legal_s_combobox")
        self.legal_s_combobox.addItem("")
        self.gridLayout_5.addWidget(self.legal_s_combobox, 2, 2, 1, 2)
        self.gridLayout_5.setColumnStretch(1, 4)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.detail_container_w)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog_REProduct)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel | QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_REProduct)
        self.buttonBox.accepted.connect(
            Dialog_REProduct.accept)  # type: ignore
        self.buttonBox.rejected.connect(
            Dialog_REProduct.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_REProduct)
        Dialog_REProduct.setTabOrder(
            self.option_sell_radio, self.option_rent_radio)
        Dialog_REProduct.setTabOrder(
            self.option_rent_radio, self.option_assignment_radio)
        Dialog_REProduct.setTabOrder(
            self.option_assignment_radio, self.pid_input)
        Dialog_REProduct.setTabOrder(self.pid_input, self.statuses_combobox)
        Dialog_REProduct.setTabOrder(
            self.statuses_combobox, self.categories_combobox)
        Dialog_REProduct.setTabOrder(
            self.categories_combobox, self.provinces_combobox)
        Dialog_REProduct.setTabOrder(
            self.provinces_combobox, self.districts_combobox)
        Dialog_REProduct.setTabOrder(
            self.districts_combobox, self.wards_combobox)
        Dialog_REProduct.setTabOrder(self.wards_combobox, self.street_input)
        Dialog_REProduct.setTabOrder(self.street_input, self.area_input)
        Dialog_REProduct.setTabOrder(self.area_input, self.structure_input)
        Dialog_REProduct.setTabOrder(self.structure_input, self.price_input)
        Dialog_REProduct.setTabOrder(self.price_input, self.function_input)
        Dialog_REProduct.setTabOrder(
            self.function_input, self.furniture_s_combobox)
        Dialog_REProduct.setTabOrder(
            self.furniture_s_combobox, self.building_line_s_combobox)
        Dialog_REProduct.setTabOrder(
            self.building_line_s_combobox, self.legal_s_combobox)
        Dialog_REProduct.setTabOrder(
            self.legal_s_combobox, self.description_input)

    def retranslateUi(self, Dialog_REProduct):
        _translate = QtCore.QCoreApplication.translate
        Dialog_REProduct.setWindowTitle(
            _translate("Dialog_REProduct", "Dialog"))
        self.image_input.setText(_translate(
            "Dialog_REProduct", "Kéo và thả hình ảnh ..."))
        self.option_sell_radio.setText(_translate("Dialog_REProduct", "Bán"))
        self.option_rent_radio.setText(
            _translate("Dialog_REProduct", "Cho thuê"))
        self.option_assignment_radio.setText(
            _translate("Dialog_REProduct", "Sang nhượng"))
        self.categories_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Loại hình BDS"))
        self.pid_label.setText(_translate("Dialog_REProduct", "PID"))
        self.statuses_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Trạng thái"))
        self.wards_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Phường"))
        self.districts_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Thành phố"))
        self.provinces_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Tỉnh"))
        self.street_label.setText(_translate("Dialog_REProduct", "Tên đường"))
        self.price_label.setText(_translate("Dialog_REProduct", "Giá"))
        self.furniture_s_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Nội thất"))
        self.building_line_s_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Lộ giới"))
        self.function_label.setText(
            _translate("Dialog_REProduct", "Công năng"))
        self.structure_label.setText(_translate("Dialog_REProduct", "Kết cấu"))
        self.area_label.setText(_translate("Dialog_REProduct", "Diện tích"))
        self.description_label.setText(
            _translate("Dialog_REProduct", "Mô tả thêm"))
        self.legal_s_combobox.setItemText(
            0, _translate("Dialog_REProduct", "Pháp lý"))
