# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.my-manager.v3/ui/page_robot.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PageRobot(object):
    def setupUi(self, PageRobot):
        PageRobot.setObjectName("PageRobot")
        PageRobot.resize(981, 640)
        PageRobot.setStyleSheet("#PageRobot{\n"
"  font-family: \"Courier New\";\n"
"  background-color: #FFFFFF;\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"}\n"
"\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(PageRobot)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.container_layout = QtWidgets.QHBoxLayout()
        self.container_layout.setContentsMargins(-1, -1, 0, -1)
        self.container_layout.setObjectName("container_layout")
        self.display_container = QtWidgets.QVBoxLayout()
        self.display_container.setSpacing(4)
        self.display_container.setObjectName("display_container")
        self.filter_container = QtWidgets.QWidget(parent=PageRobot)
        self.filter_container.setObjectName("filter_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.filter_container)
        self.horizontalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.username_container_2 = QtWidgets.QGroupBox(parent=self.filter_container)
        self.username_container_2.setTitle("")
        self.username_container_2.setObjectName("username_container_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.username_container_2)
        self.verticalLayout_21.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_21.setSpacing(4)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.username_label_2 = QtWidgets.QLabel(parent=self.username_container_2)
        self.username_label_2.setStyleSheet("font-size: 10px")
        self.username_label_2.setObjectName("username_label_2")
        self.verticalLayout_22.addWidget(self.username_label_2)
        self.username_input_2 = QtWidgets.QLineEdit(parent=self.username_container_2)
        self.username_input_2.setObjectName("username_input_2")
        self.verticalLayout_22.addWidget(self.username_input_2)
        self.verticalLayout_21.addLayout(self.verticalLayout_22)
        self.horizontalLayout_7.addWidget(self.username_container_2)
        self.group_container_2 = QtWidgets.QGroupBox(parent=self.filter_container)
        self.group_container_2.setTitle("")
        self.group_container_2.setObjectName("group_container_2")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.group_container_2)
        self.verticalLayout_23.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_23.setSpacing(4)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.group_label_2 = QtWidgets.QLabel(parent=self.group_container_2)
        self.group_label_2.setStyleSheet("font-size: 10px")
        self.group_label_2.setObjectName("group_label_2")
        self.verticalLayout_24.addWidget(self.group_label_2)
        self.group_input_2 = QtWidgets.QLineEdit(parent=self.group_container_2)
        self.group_input_2.setObjectName("group_input_2")
        self.verticalLayout_24.addWidget(self.group_input_2)
        self.verticalLayout_23.addLayout(self.verticalLayout_24)
        self.horizontalLayout_7.addWidget(self.group_container_2)
        self.note_container_2 = QtWidgets.QGroupBox(parent=self.filter_container)
        self.note_container_2.setTitle("")
        self.note_container_2.setObjectName("note_container_2")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.note_container_2)
        self.verticalLayout_25.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_25.setSpacing(4)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.note_label_2 = QtWidgets.QLabel(parent=self.note_container_2)
        self.note_label_2.setStyleSheet("font-size: 10px")
        self.note_label_2.setObjectName("note_label_2")
        self.verticalLayout_26.addWidget(self.note_label_2)
        self.note_input_2 = QtWidgets.QLineEdit(parent=self.note_container_2)
        self.note_input_2.setObjectName("note_input_2")
        self.verticalLayout_26.addWidget(self.note_input_2)
        self.verticalLayout_25.addLayout(self.verticalLayout_26)
        self.horizontalLayout_7.addWidget(self.note_container_2)
        self.type_container_2 = QtWidgets.QGroupBox(parent=self.filter_container)
        self.type_container_2.setTitle("")
        self.type_container_2.setObjectName("type_container_2")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.type_container_2)
        self.verticalLayout_27.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_27.setSpacing(4)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.type_label_2 = QtWidgets.QLabel(parent=self.type_container_2)
        self.type_label_2.setStyleSheet("font-size: 10px")
        self.type_label_2.setObjectName("type_label_2")
        self.verticalLayout_28.addWidget(self.type_label_2)
        self.type_input_2 = QtWidgets.QLineEdit(parent=self.type_container_2)
        self.type_input_2.setObjectName("type_input_2")
        self.verticalLayout_28.addWidget(self.type_input_2)
        self.verticalLayout_27.addLayout(self.verticalLayout_28)
        self.horizontalLayout_7.addWidget(self.type_container_2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.display_container.addWidget(self.filter_container)
        self.robot_table_container = QtWidgets.QWidget(parent=PageRobot)
        self.robot_table_container.setObjectName("robot_table_container")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.robot_table_container)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.users_table = QtWidgets.QTableView(parent=self.robot_table_container)
        self.users_table.setObjectName("users_table")
        self.horizontalLayout.addWidget(self.users_table)
        self.actions_tree = QtWidgets.QTreeWidget(parent=self.robot_table_container)
        self.actions_tree.setObjectName("actions_tree")
        self.horizontalLayout.addWidget(self.actions_tree)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        self.display_container.addWidget(self.robot_table_container)
        self.container_layout.addLayout(self.display_container)
        self.actions_container = QtWidgets.QWidget(parent=PageRobot)
        self.actions_container.setMinimumSize(QtCore.QSize(300, 0))
        self.actions_container.setObjectName("actions_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.actions_container)
        self.verticalLayout_3.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.actions_container_layout = QtWidgets.QVBoxLayout()
        self.actions_container_layout.setContentsMargins(-1, -1, -1, 0)
        self.actions_container_layout.setSpacing(4)
        self.actions_container_layout.setObjectName("actions_container_layout")
        self.action_payload_container_layout = QtWidgets.QVBoxLayout()
        self.action_payload_container_layout.setObjectName("action_payload_container_layout")
        self.actions_container_layout.addLayout(self.action_payload_container_layout)
        self.action_add_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_add_btn.setObjectName("action_add_btn")
        self.actions_container_layout.addWidget(self.action_add_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.actions_container_layout.addItem(spacerItem)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.action_save_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_save_btn.setObjectName("action_save_btn")
        self.horizontalLayout_9.addWidget(self.action_save_btn)
        self.action_run_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.action_run_btn.setObjectName("action_run_btn")
        self.horizontalLayout_9.addWidget(self.action_run_btn)
        self.actions_container_layout.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.actions_container_layout)
        self.log_message = QtWidgets.QPlainTextEdit(parent=self.actions_container)
        self.log_message.setObjectName("log_message")
        self.verticalLayout_3.addWidget(self.log_message)
        self.container_layout.addWidget(self.actions_container)
        self.horizontalLayout_2.addLayout(self.container_layout)

        self.retranslateUi(PageRobot)
        QtCore.QMetaObject.connectSlotsByName(PageRobot)

    def retranslateUi(self, PageRobot):
        _translate = QtCore.QCoreApplication.translate
        PageRobot.setWindowTitle(_translate("PageRobot", "Form"))
        self.username_label_2.setText(_translate("PageRobot", "Username"))
        self.group_label_2.setText(_translate("PageRobot", "Group"))
        self.note_label_2.setText(_translate("PageRobot", "Note"))
        self.type_label_2.setText(_translate("PageRobot", "Type"))
        self.action_add_btn.setText(_translate("PageRobot", "Add action"))
        self.action_save_btn.setText(_translate("PageRobot", "Save"))
        self.action_run_btn.setText(_translate("PageRobot", "Run"))
