# Form implementation generated from reading ui file '/Volumes/KINGSTON/Dev/python/python.my-manager.v3/ui/page_robot.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PageRobot(object):
    def setupUi(self, PageRobot):
        PageRobot.setObjectName("PageRobot")
        PageRobot.resize(981, 640)
        PageRobot.setStyleSheet("#PageRobot{\n"
"  font-family: \"Courier New\";\n"
"  background-color: #FFFFFF;\n"
"}\n"
"QGroupBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  background-color: rgba(248, 249, 250, 1);\n"
"}\n"
"QLineEdit {\n"
"  padding: 4px 0;\n"
"  border: 1px solid #ced4da;\n"
"  border-radius: 8px;\n"
"  margin-left: 8px;\n"
"  padding-left: 4px;\n"
"  background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QPlainTextEdit {\n"
"    background-color: #FFFFFF;\n"
"  color:#212529;\n"
"}\n"
"QLabel {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: rgb(90, 93, 97);\n"
"}\n"
"QRadioButton {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QComboBox {\n"
"  font-family: \"Courier New\";\n"
"  font-size: 13px;\n"
"  color: #212529;\n"
"}\n"
"QPushButton {\n"
"  color: #212529;\n"
"}\n"
"\n"
"")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(PageRobot)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.container_layout = QtWidgets.QHBoxLayout()
        self.container_layout.setContentsMargins(-1, -1, 0, -1)
        self.container_layout.setObjectName("container_layout")
        self.user_container = QtWidgets.QWidget(parent=PageRobot)
        self.user_container.setObjectName("user_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.user_container)
        self.horizontalLayout.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_layout = QtWidgets.QVBoxLayout()
        self.user_layout.setContentsMargins(-1, -1, -1, 0)
        self.user_layout.setObjectName("user_layout")
        self.filter_layout = QtWidgets.QHBoxLayout()
        self.filter_layout.setContentsMargins(-1, -1, 0, -1)
        self.filter_layout.setObjectName("filter_layout")
        self.username_container = QtWidgets.QGroupBox(parent=self.user_container)
        self.username_container.setTitle("")
        self.username_container.setObjectName("username_container")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.username_container)
        self.verticalLayout_19.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_19.setSpacing(4)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.username_label = QtWidgets.QLabel(parent=self.username_container)
        self.username_label.setStyleSheet("font-size: 10px")
        self.username_label.setObjectName("username_label")
        self.verticalLayout_20.addWidget(self.username_label)
        self.username_input = QtWidgets.QLineEdit(parent=self.username_container)
        self.username_input.setObjectName("username_input")
        self.verticalLayout_20.addWidget(self.username_input)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.filter_layout.addWidget(self.username_container)
        self.type_container = QtWidgets.QGroupBox(parent=self.user_container)
        self.type_container.setTitle("")
        self.type_container.setObjectName("type_container")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.type_container)
        self.verticalLayout_15.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_15.setSpacing(4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.type_label = QtWidgets.QLabel(parent=self.type_container)
        self.type_label.setStyleSheet("font-size: 10px")
        self.type_label.setObjectName("type_label")
        self.verticalLayout_16.addWidget(self.type_label)
        self.type_input = QtWidgets.QLineEdit(parent=self.type_container)
        self.type_input.setObjectName("type_input")
        self.verticalLayout_16.addWidget(self.type_input)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.filter_layout.addWidget(self.type_container)
        self.group_container = QtWidgets.QGroupBox(parent=self.user_container)
        self.group_container.setTitle("")
        self.group_container.setObjectName("group_container")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.group_container)
        self.verticalLayout_13.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_13.setSpacing(4)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.group_label = QtWidgets.QLabel(parent=self.group_container)
        self.group_label.setStyleSheet("font-size: 10px")
        self.group_label.setObjectName("group_label")
        self.verticalLayout_14.addWidget(self.group_label)
        self.group_input = QtWidgets.QLineEdit(parent=self.group_container)
        self.group_input.setObjectName("group_input")
        self.verticalLayout_14.addWidget(self.group_input)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.filter_layout.addWidget(self.group_container)
        self.note_container = QtWidgets.QGroupBox(parent=self.user_container)
        self.note_container.setTitle("")
        self.note_container.setObjectName("note_container")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.note_container)
        self.verticalLayout_17.setContentsMargins(2, 4, 4, 2)
        self.verticalLayout_17.setSpacing(4)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.note_label = QtWidgets.QLabel(parent=self.note_container)
        self.note_label.setStyleSheet("font-size: 10px")
        self.note_label.setObjectName("note_label")
        self.verticalLayout_18.addWidget(self.note_label)
        self.note_input = QtWidgets.QLineEdit(parent=self.note_container)
        self.note_input.setObjectName("note_input")
        self.verticalLayout_18.addWidget(self.note_input)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        self.filter_layout.addWidget(self.note_container)
        self.user_layout.addLayout(self.filter_layout)
        self.users_table = QtWidgets.QTableView(parent=self.user_container)
        self.users_table.setObjectName("users_table")
        self.user_layout.addWidget(self.users_table)
        self.horizontalLayout.addLayout(self.user_layout)
        self.container_layout.addWidget(self.user_container)
        self.actions_container = QtWidgets.QWidget(parent=PageRobot)
        self.actions_container.setObjectName("actions_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.actions_container)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.actions_container_layout = QtWidgets.QVBoxLayout()
        self.actions_container_layout.setContentsMargins(-1, -1, -1, 16)
        self.actions_container_layout.setObjectName("actions_container_layout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.actions_container)
        self.tabWidget.setObjectName("tabWidget")
        self.new_action = QtWidgets.QWidget()
        self.new_action.setObjectName("new_action")
        self.tabWidget.addTab(self.new_action, "")
        self.actions_container_layout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.save_actions_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.save_actions_btn.setObjectName("save_actions_btn")
        self.horizontalLayout_3.addWidget(self.save_actions_btn)
        self.run_actions_btn = QtWidgets.QPushButton(parent=self.actions_container)
        self.run_actions_btn.setObjectName("run_actions_btn")
        self.horizontalLayout_3.addWidget(self.run_actions_btn)
        self.actions_container_layout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.actions_container_layout)
        self.container_layout.addWidget(self.actions_container)
        self.horizontalLayout_2.addLayout(self.container_layout)

        self.retranslateUi(PageRobot)
        QtCore.QMetaObject.connectSlotsByName(PageRobot)

    def retranslateUi(self, PageRobot):
        _translate = QtCore.QCoreApplication.translate
        PageRobot.setWindowTitle(_translate("PageRobot", "Form"))
        self.username_label.setText(_translate("PageRobot", "Username"))
        self.type_label.setText(_translate("PageRobot", "Type"))
        self.group_label.setText(_translate("PageRobot", "Group"))
        self.note_label.setText(_translate("PageRobot", "Note"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.new_action), _translate("PageRobot", "New action"))
        self.save_actions_btn.setText(_translate("PageRobot", "Save"))
        self.run_actions_btn.setText(_translate("PageRobot", "Run"))
